In [1]:
import json
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

dataset_name = ["MTBench", "HumanEval", "GSM8K", "XSUM", "CNN/DM"]

def simplify_dataset_name(name):
    # 把传入的 name 也去掉所有非字母字符并转为小写
    # "eval/eval_mt_bench_noeval.py" -> "evalevalmtbenchnoevalpy"
    clean_name = "".join(filter(str.isalpha, name)).lower()
    
    for d in dataset_name:
        # "MTBench" -> "mtbench"
        clean_d = "".join(filter(str.isalpha, d)).lower()
        if clean_d in clean_name:
            return d
    return name

method_mapping = {
    "adaptive_tridecoding": "CEE-SD",
    "tridecoding": "TriDecoding",
    "dist_split_spec": "DSSD",
    "dist_spec": "DSD",
    "large": "AR",
    "cee_dsd": "CEE-DSD",
    "cee_dssd": "CEE-DSSD",
    "cee_cuhlm": "CEE-CUHLM",
    
}

simplify_method_name = lambda method: method_mapping.get(method, method)

def read_experiment_data(file_path):
    """读取实验数据文件"""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


def extract_experiment_info(experiments):
    """提取实验信息"""
    results = []

    for exp in experiments:
        config = exp.get("config", {})
        result = exp.get("result", {})

        # 提取所需的参数
        eval_dataset = config.get("eval_dataset", "N/A")
        edge_cloud_bandwidth = config.get("edge_cloud_bandwidth", 0)
        edge_end_bandwidth = config.get("edge_end_bandwidth", 0)
        eval_mode = result.get("eval_mode", "")
        accuracy = result.get("accuracy", "N/A")  # 提取 accuracy
        target_forward_times = result.get("target_forward_times", 0)
        generated_tokens = result.get("generated_tokens", 0)
        wall_time = result.get("wall_time", 0)
        communication_time = result.get("communication_time", 0)
        queuing_time = result.get("queuing_time", 0)
        edge_cloud_data_bytes = result.get("edge_cloud_data_bytes", 0)
        throughput = result.get("throughput", 0)
        comm_energy = result.get("comm_energy", 0)

        
        # 提取模型信息
        little_model = result.get("little_model") or config.get("little_model", "N/A")
        draft_model = result.get("draft_model") or config.get("draft_model", "N/A")
        target_model = result.get("target_model") or config.get("target_model", "N/A")
        
        # 为了美观，可以去掉路径前缀
        def simplify_model_name(name):
            if isinstance(name, str) and "/" in name:
                return name.split("/")[-1]
            return name
            
        little_model = simplify_model_name(little_model)
        draft_model = simplify_model_name(draft_model)
        target_model = simplify_model_name(target_model)

        # 提取接受率相关数据
        little_accepted_tokens = result.get("little_accepted_tokens", 0)
        little_generated_tokens = result.get("little_generated_tokens", 0)
        draft_accepted_tokens = result.get("draft_accepted_tokens", 0)
        draft_generated_tokens = result.get("draft_generated_tokens", 0)

        # 计算接受率
        draft_acc = (
            round(little_accepted_tokens / little_generated_tokens * 100, 2)
            if little_generated_tokens > 0
            else "N/A"
        )
        target_acc = (
            round(draft_accepted_tokens / draft_generated_tokens * 100, 2)
            if draft_generated_tokens > 0
            else "N/A"
        )

        # 兼容传统 Speculation
        if target_acc == "N/A" and "acceptance_rate" in result:
            target_acc = round(float(result["acceptance_rate"]) * 100, 2)

        results.append(
            {
                "数据集": simplify_dataset_name(eval_dataset),
                "Edge-Cloud 带宽 (Mbps)": edge_cloud_bandwidth,
                "Edge-End 带宽 (Mbps)": edge_end_bandwidth,
                "方法": simplify_method_name(eval_mode),
                "Little-Model": little_model,
                "Draft-Model": draft_model,
                "Target-Model": target_model,
                "准确率": accuracy,  # 添加到结果中
                "生成 Token 数": generated_tokens,
                "目标模型 Forward 次数": target_forward_times,
                "目标模型 Forward/Token": round(target_forward_times / generated_tokens, 4) if generated_tokens > 0 else None,
                "Draft 接受率 (%)": draft_acc,
                "Target 接受率 (%)": target_acc,
                "挂钟时间 (s)": round(wall_time, 2),
                "通信时间 (s)": round(communication_time, 2),
                "排队时间 (s)": round(queuing_time, 2),
                "Edge-Cloud 数据传输量 (Mbytes)": round(edge_cloud_data_bytes / (1024 * 1024), 2),
                "Token 输出速率 (tokens/s)": round(throughput, 2),
                # "通信能量": comm_energy,
                "Gamma1:": config.get("gamma1", "N/A"),
            }
        )

    return results

def process_data(experiment_data):
    """处理实验数据，计算相对算力消耗并转换为DataFrame"""
    df = pd.DataFrame(experiment_data)

    # 找到 large 方法的基准值
    # 假设每个数据集都有一个 large 实验作为基准
    large_df = df[df['方法'] == 'large'][['数据集', '目标模型 Forward 次数']].drop_duplicates(subset=['数据集'])
    large_df = large_df.rename(columns={'目标模型 Forward 次数': 'baseline_forwards'})

    # 合并基准值
    df = pd.merge(df, large_df, on='数据集', how='left')

    # 计算相对 large 算力消耗 (%)
    # df['相对 large 算力消耗 (%)'] = df.apply(
    #     lambda row: round((row['目标模型 Forward 次数'] / row['baseline_forwards'] * 100), 2)
    #     if pd.notnull(row['baseline_forwards']) and row['baseline_forwards'] > 0
    #     else None,
    #     axis=1
    # )
    
    # Ratio used to compare cloud-model computation after normalizing by output length.
    df['目标模型 Forward/Token'] = df.apply(
        lambda row: round(row['目标模型 Forward 次数'] / row['生成 Token 数'], 4) if row['生成 Token 数'] > 0 else None,
        axis=1
    )

    df['每Token 平均通信时间 (s)'] = df.apply(
        lambda row: round(row['通信时间 (s)'] / row['生成 Token 数'], 4) if row['生成 Token 数'] > 0 else None,
        axis=1
    )

    df['每token平均WAN通信数据量 (bytes)'] = df.apply(
        lambda row: round((row['Edge-Cloud 数据传输量 (Mbytes)'] * 1024 * 1024) / row['生成 Token 数'], 2) if row['生成 Token 数'] > 0 else None,
        axis=1
    )   

    # 清理临时列
    if 'baseline_forwards' in df.columns:
        del df['baseline_forwards']

    if 'Edge-Cloud 数据传输量 (Mbytes)' in df.columns:
        del df['Edge-Cloud 数据传输量 (Mbytes)']
    
    return df

def generate_markdown_table(df):
    """生成 markdown 表格"""
    # 按方法分组，然后按Edge-Cloud带宽降序排序
    df_sorted = df.sort_values(
        ["方法", "Edge-Cloud 带宽 (Mbps)"], ascending=[True, False]
    )

    # 生成 markdown 表格
    markdown_table = df_sorted.to_markdown(index=False, tablefmt="github")
    return markdown_table


def get_pandas_table(df):
    """生成 pandas DataFrame 表格"""
    # 按方法分组，然后按Edge-Cloud带宽降序排序
    df_sorted = df.sort_values(
        ["方法", "Edge-Cloud 带宽 (Mbps)"], ascending=[True, False]
    )
    return df_sorted


def generate_grouped_tables(df):
    """按方法分组生成多个表格"""
    # 按方法分组
    grouped = df.groupby("方法")

    all_tables = []

    for method, group_df in grouped:
        # 按Edge-Cloud带宽降序排序
        group_df_sorted = group_df.sort_values(
            "Edge-Cloud 带宽 (Mbps)", ascending=False
        )

        # 生成表格
        table = group_df_sorted.to_markdown(index=False, tablefmt="github")

        all_tables.append(f"## 方法: {method}\n\n{table}\n")

    return "\n".join(all_tables)


def generate_dataset_grouped_tables(df):
    """按数据集分组生成多个表格"""
    # 按数据集分组
    grouped = df.groupby("数据集")

    all_tables = []

    for dataset, group_df in grouped:
        # 排序：按方法排序，带宽降序
        group_df_sorted = group_df.sort_values(
            ["方法", "Edge-Cloud 带宽 (Mbps)"], ascending=[True, False]
        )

        # 生成表格
        table = group_df_sorted.to_markdown(index=False, tablefmt="github")

        all_tables.append(f"## 数据集: {dataset}\n\n{table}\n")

    return "\n".join(all_tables)


def generate_per_dataset_avg_table(df):
    """按数据集生成各方法平均对比表（跨模型系列平均）"""
    all_tables = []
    for dataset in sorted(df["数据集"].unique()):
        ds_df = df[df["数据集"] == dataset]
        avg_table = ds_df.groupby("方法").mean(numeric_only=True).round(2)
        avg_table = avg_table.sort_values("Token 输出速率 (tokens/s)", ascending=False)
        table = avg_table.to_markdown(tablefmt="github")
        all_tables.append(f"## 数据集: {dataset} (跨系列平均)\n\n{table}\n")
    return "\n".join(all_tables)


def jupyter_display_per_dataset_avg(df):
    """在 Jupyter 中显示各数据集平均方法对比"""
    for dataset in sorted(df["数据集"].unique()):
        display(Markdown(f"## 数据集: {dataset} (跨模型系列平均)"))
        ds_df = df[df["数据集"] == dataset]
        avg_table = ds_df.groupby("方法").mean(numeric_only=True).round(4)
        avg_table = avg_table.sort_values("Token 输出速率 (tokens/s)", ascending=False)

        display(avg_table)



def jupyter_display(df):
    """
    一个专门为 Jupyter Notebook 设计的主函数，
    用于读取、处理数据并以美观的表格形式显示结果。
    """
    # --- 1. 显示统一排序的表格 ---
    # 使用 display(Markdown(...)) 来渲染标题
    display(Markdown("# 实验结果对比表（按方法和带宽排序）"))

    # 对 DataFrame 进行排序
    df_sorted = df.sort_values(
        ["方法", "Edge-Cloud 带宽 (Mbps)"], ascending=[True, False]
    )

    # 直接显示 DataFrame 对象，Jupyter 会将其渲染为 HTML 表格
    display(df_sorted)
    
    # --- 2. 显示按方法分组的表格 ---
    display(Markdown("# 实验结果对比表（按方法分组）"))

    # 按方法进行分组
    grouped = df.groupby("方法")
    # 遍历每个分组并分别显示
    for method, group_df in grouped:
        # 显示分组标题
        display(Markdown(f"## 方法: {method}"))

        # 对当前分组的 DataFrame 进行排序
        group_df_sorted = group_df.sort_values(
            "Edge-Cloud 带宽 (Mbps)", ascending=False
        )

        # 显示排序后的分组 DataFrame
        display(group_df_sorted)

    # --- 4. 显示各数据集方法平均对比表（跨模型系列平均） ---
    display(Markdown("# 各数据集方法平均对比 (跨模型系列)"))
    jupyter_display_per_dataset_avg(df)

    # --- 3. 显示按数据集分组的表格 ---
    display(Markdown("# 实验结果对比表（按数据集分组）"))

    # 按数据集进行分组
    grouped_ds = df.groupby("数据集")
    for dataset, group_df in grouped_ds:
        # 显示分组标题
        display(Markdown(f"## 数据集: {dataset}"))

        # 排序：按方法排序，带宽降序
        group_df_sorted = group_df.sort_values(
            ["方法", "Edge-Cloud 带宽 (Mbps)"], ascending=[True, False]
        )

        # 显示排序后的分组 DataFrame
        display(group_df_sorted)


def main(specified_file=None):
    # 读取实验数据
    import glob
    import os
    
    file_path = None
    candidate_dirs = [Path('experiment_results'), Path('../experiment_results'), Path('.')]
    results_dir = next((path for path in candidate_dirs if path.exists()), Path('experiment_results'))
    
    # 1. 优先使用用户指定的文件
    if specified_file:
        if os.path.exists(specified_file):
            file_path = specified_file
        else:
            print(f"指定的文件不存在: {specified_file}")
            return

    # 2. 如果没有指定文件，则寻找最新的 experiment_summary_*.json
    if not file_path:
        json_files = glob.glob(str(results_dir / "experiment_summary_*.json"))
        if json_files:
            file_path = max(json_files, key=os.path.getmtime)
        else:
            # 3. 最后的兜底
            target_file = results_dir / "experiment_summary_20260127_053240.json"
            if os.path.exists(target_file):
                file_path = str(target_file)
            else:
                print("找不到任何实验总结 JSON 文件")
                return
            
    print(f"处理文件: {file_path}")

    experiments = read_experiment_data(file_path)
    experiment_data = extract_experiment_info(experiments)

    # process data to dataframe and add new metrics
    df = process_data(experiment_data)

    unified_table = generate_markdown_table(df)
    method_grouped_tables = generate_grouped_tables(df)
    dataset_grouped_tables = generate_dataset_grouped_tables(df)

    jupyter_display(df)

    # 保存到文件
    with open("experiment_results_table.md", "w", encoding="utf-8") as f:
        f.write("# 实验结果对比表\n\n")
        f.write("## 1. 统一对比表（按方法和带宽排序）\n\n")
        f.write(unified_table)
        f.write("\n\n" + "=" * 80 + "\n\n")
        f.write("## 2. 按方法分组表格\n\n")
        f.write(method_grouped_tables)
        f.write("\n\n" + "=" * 80 + "\n\n")
        f.write("## 3. 按数据集分组表格\n\n")
        f.write("\n\n" + "=" * 80 + "\n\n")
        f.write("## 4. 各数据集方法平均对比表\n\n")
        per_dataset_avg = generate_per_dataset_avg_table(df)
        f.write(per_dataset_avg)

    print("\n表格已保存到 experiment_results_table.md 文件中")


if __name__ == "__main__":
    # 如果想指定文件，请修改下一行，例如: main("experiment_results/experiment_summary_20260127_053240.json")
    main()

处理文件: ../experiment_results/experiment_summary_fluid_gamma_20261010.json

# 实验结果对比表（按方法和带宽排序）

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
12,MTBench,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.15,77.64,824.06,242.01,238.45,24.61,5,0.0119,158.71
27,GSM8K,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2922,0.2854,55.89,73.27,499.86,149.26,146.10,20.49,5,0.0146,314.37
42,HumanEval,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1787,0.1745,44.57,90.35,332.56,91.08,89.35,30.79,5,0.0089,101.38
57,MTBench,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6444,0.3592,58.02,49.13,1049.80,330.24,322.20,17.09,5,0.0184,634.83
72,GSM8K,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10197,2910,0.2854,76.79,67.21,474.62,150.65,145.50,21.48,5,0.0148,821.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,GSM8K,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1500,10236,4837,0.4725,N/A,53.79,690.81,259.19,241.85,14.82,3,0.0253,481.47
83,HumanEval,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10225,3550,0.3472,N/A,37.91,521.65,192.59,177.50,19.60,3,0.0188,357.90
98,MTBench,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1544.43,487.84,451.80,13.30,3,0.0238,445.18
113,GSM8K,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10258,3281,0.3198,N/A,27.54,591.24,180.58,164.05,17.35,3,0.0176,333.24
128,HumanEval,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0000,10263,4060,0.3956,N/A,35.31,703.64,219.86,203.00,14.59,3,0.0214,404.60

# 实验结果对比表（按方法分组）

## 方法: CEE-SD

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
12,MTBench,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.15,77.64,824.06,242.01,238.45,24.61,5,0.0119,158.71
27,GSM8K,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2922,0.2854,55.89,73.27,499.86,149.26,146.10,20.49,5,0.0146,314.37
42,HumanEval,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1787,0.1745,44.57,90.35,332.56,91.08,89.35,30.79,5,0.0089,101.38
117,GSM8K,46.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,483.45,117.71,115.95,21.18,5,0.0115,130.05
102,MTBench,46.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1150.05,290.18,286.20,17.81,5,0.0142,173.57
87,HumanEval,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1820,0.1783,77.9,77.27,326.20,92.22,91.00,31.29,5,0.0090,50.33
72,GSM8K,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10197,2910,0.2854,76.79,67.21,474.62,150.65,145.50,21.48,5,0.0148,821.63
57,MTBench,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6444,0.3592,58.02,49.13,1049.80,330.24,322.20,17.09,5,0.0184,634.83
118,GSM8K,10.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,485.42,121.22,115.95,21.10,5,0.0118,130.05
88,HumanEval,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1819,0.1782,77.9,77.21,326.61,94.35,90.95,31.25,5,0.0092,49.31
28,GSM8K,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2923,0.2854,55.88,73.18,506.63,156.14,146.15,20.21,5,0.0152,320.51
43,HumanEval,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1787,0.1745,44.57,90.35,336.65,94.91,89.35,30.42,5,0.0093,101.38
13,MTBench,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.14,77.68,831.02,248.87,238.45,24.41,5,0.0123,158.19
103,MTBench,10.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1157.93,297.52,286.20,17.69,5,0.0145,173.57
73,GSM8K,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10193,2917,0.2862,76.91,67.25,488.75,164.56,145.85,20.86,5,0.0161,890.87
58,MTBench,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6462,0.3602,57.89,48.85,1073.75,352.04,323.10,16.71,5,0.0196,774.54
29,GSM8K,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2924,0.2855,55.8,73.13,514.51,163.52,146.20,19.90,5,0.0160,321.54
14,MTBench,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.12,77.68,838.70,256.82,238.45,24.18,5,0.0127,158.19
44,HumanEval,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1787,0.1745,44.57,90.35,341.23,99.38,89.35,30.01,5,0.0097,101.38
59,MTBench,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6462,0.3602,57.89,48.85,1095.56,374.16,323.10,16.37,5,0.0209,786.81
74,GSM8K,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10193,2920,0.2865,76.93,67.13,502.57,178.12,146.00,20.28,5,0.0175,899.10
89,HumanEval,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1819,0.1782,77.9,77.21,328.94,97.03,90.95,31.03,5,0.0095,49.31
104,MTBench,5.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1166.31,306.04,286.20,17.56,5,0.0149,173.57
119,GSM8K,5.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,489.76,125.20,115.95,20.91,5,0.0122,130.05

## 方法: DSD

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
0,MTBench,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,7883,0.3849,N/A,54.02,1565.61,776.46,394.15,13.08,3,0.0379,87455.74
30,HumanEval,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,4912,0.4797,N/A,36.79,982.81,481.41,245.60,10.42,3,0.0470,113674.24
15,GSM8K,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,4566,0.4459,N/A,42.06,914.31,449.11,228.30,11.20,3,0.0439,105157.63
45,MTBench,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18003,7860,0.4366,N/A,43.89,2586.83,1843.51,393.00,6.96,3,0.1024,485829.15
90,MTBench,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,7643,0.3732,N/A,57.01,2693.97,1742.92,382.15,7.60,3,0.0851,398462.46
75,HumanEval,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,3114,0.3051,N/A,76.98,1008.16,710.82,155.70,10.13,3,0.0696,302622.24
120,HumanEval,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0000,10240,3538,0.3455,N/A,64.18,1253.68,810.84,176.90,8.17,3,0.0792,360761.34
105,GSM8K,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,3319,0.3241,N/A,70.54,1182.32,761.56,165.95,8.66,3,0.0744,330850.30
60,GSM8K,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,3511,0.3437,N/A,64.51,1143.02,806.70,175.55,8.94,3,0.0790,358582.20
46,MTBench,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18030,11003,0.6103,N/A,64.46,5139.06,4200.72,550.15,3.51,3,0.2330,249702.41
1,MTBench,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,11919,0.5820,N/A,72.40,2585.39,1413.07,595.95,7.92,3,0.0690,47171.58
121,HumanEval,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0000,10240,5721,0.5587,N/A,79.63,2572.78,1936.10,286.05,3.98,3,0.1891,202740.74
91,MTBench,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,11796,0.5760,N/A,74.26,5487.25,4180.76,589.80,3.73,3,0.2041,218199.55
76,HumanEval,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,5436,0.5325,N/A,88.45,2186.70,1720.65,271.80,4.67,3,0.1686,179203.98
31,HumanEval,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,6546,0.6393,N/A,56.90,1464.94,809.06,327.30,6.99,3,0.0790,58100.74
16,GSM8K,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,6335,0.6187,N/A,62.06,1408.46,775.30,316.75,7.27,3,0.0757,54278.14
106,GSM8K,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,5605,0.5474,N/A,83.38,2474.64,1844.62,280.25,4.14,3,0.1801,192415.74
61,GSM8K,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10214,5711,0.5591,N/A,79.41,2431.28,1940.00,285.55,4.20,3,0.1899,203526.82
2,MTBench,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,11919,0.5820,N/A,72.40,3234.91,2062.27,595.95,6.33,3,0.1007,47171.58
32,HumanEval,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,6546,0.6393,N/A,56.90,1881.04,1225.37,327.30,5.44,3,0.1197,58100.74
17,GSM8K,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,6335,0.6187,N/A,62.06,1777.96,1144.41,316.75,5.76,3,0.1118,54278.14
47,MTBench,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18030,11003,0.6103,N/A,64.46,8690.73,7752.23,550.15,2.07,3,0.4300,249702.41
62,GSM8K,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10214,5711,0.5591,N/A,79.41,4051.13,3558.90,285.55,2.52,3,0.3484,203526.82
77,HumanEval,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,5436,0.5325,N/A,88.45,3658.35,3192.38,271.80,2.79,3,0.3127,179203.98
92,MTBench,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,11796,0.5760,N/A,74.26,8993.60,7683.47,589.80,2.28,3,0.3752,218199.55
107,GSM8K,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,5605,0.5474,N/A,83.38,4011.39,3382.66,280.25,2.55,3,0.3303,192415.74
122,HumanEval,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0000,10240,5721,0.5587,N/A,79.63,4187.64,3550.70,286.05,2.45,3,0.3467,202740.74

## 方法: DSSD

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
3,MTBench,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,808.92,247.44,188.25,25.32,3,0.0121,6735.36
33,HumanEval,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1471,0.1437,N/A,77.12,324.30,94.13,73.55,31.58,3,0.0092,2962.43
18,GSM8K,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,468.38,143.87,106.70,21.86,3,0.0140,9293.82
48,MTBench,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,1750.88,758.75,352.85,10.31,3,0.0420,107093.35
93,MTBench,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,1385.47,504.45,240.90,14.78,3,0.0246,55334.91
78,HumanEval,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1709,0.1674,N/A,64.89,408.95,164.94,85.45,24.96,3,0.0162,24246.27
123,HumanEval,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0000,10240,2167,0.2116,N/A,48.26,626.39,227.27,108.35,16.35,3,0.0222,47172.61
108,GSM8K,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,553.36,193.14,96.40,18.50,3,0.0189,35953.66
63,GSM8K,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,558.37,236.39,112.10,18.29,3,0.0231,48449.04
49,MTBench,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,2835.14,1842.03,352.85,6.37,3,0.1020,107093.35
4,MTBench,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,925.71,364.71,188.25,22.12,3,0.0178,6735.36
124,HumanEval,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0000,10240,2167,0.2116,N/A,48.26,923.71,524.41,108.35,11.09,3,0.0512,47172.61
94,MTBench,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,2065.31,1184.06,240.90,9.92,3,0.0578,55334.91
79,HumanEval,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1709,0.1674,N/A,64.89,569.46,325.54,85.45,17.93,3,0.0319,24246.27
34,HumanEval,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1471,0.1437,N/A,77.12,361.32,131.08,73.55,28.34,3,0.0128,2962.43
19,GSM8K,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,542.04,217.23,106.70,18.89,3,0.0212,9293.82
109,GSM8K,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,782.96,423.88,96.40,13.08,3,0.0414,35953.66
64,GSM8K,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,862.40,539.85,112.10,11.84,3,0.0528,48449.04
5,MTBench,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,1045.92,485.23,188.25,19.58,3,0.0237,6735.36
35,HumanEval,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0000,10240,1471,0.1437,N/A,77.12,393.58,163.44,73.55,26.02,3,0.0160,2962.43
20,GSM8K,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,622.55,298.42,106.70,16.45,3,0.0291,9293.82
50,MTBench,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,4409.62,3416.29,352.85,4.09,3,0.1892,107093.35
65,GSM8K,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,1190.86,868.79,112.10,8.58,3,0.0851,48449.04
80,HumanEval,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1709,0.1674,N/A,64.89,747.20,503.26,85.45,13.66,3,0.0493,24246.27
95,MTBench,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,2840.80,1959.39,240.90,7.21,3,0.0957,55334.91
110,GSM8K,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,1043.63,684.55,96.40,9.81,3,0.0669,35953.66
125,HumanEval,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0000,10240,2167,0.2116,N/A,48.26,1253.31,853.75,108.35,8.17,3,0.0834,47172.61

## 方法: tk_slt

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
9,MTBench,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,927.08,309.65,297.20,22.09,3,0.0151,1454.59
24,GSM8K,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,614.78,201.37,195.00,16.66,3,0.0197,1906.69
39,HumanEval,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,4193,0.4095,N/A,18.77,660.96,216.08,209.65,15.49,3,0.0211,2037.76
129,HumanEval,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0000,10240,2416,0.2359,N/A,42.10,509.75,126.70,120.80,20.09,3,0.0124,1180.67
114,GSM8K,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,456.51,112.22,106.25,22.43,3,0.0110,1050.62
99,MTBench,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1191.44,296.86,285.40,17.19,3,0.0145,1384.45
84,HumanEval,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1857,0.1819,N/A,58.03,320.18,98.54,92.85,31.88,3,0.0097,921.41
69,GSM8K,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,414.04,126.45,120.30,24.67,3,0.0124,1192.80
54,MTBench,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1124.42,344.47,332.35,16.06,3,0.0191,1841.99
115,GSM8K,10.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,472.29,129.67,106.25,21.68,3,0.0127,1050.62
100,MTBench,10.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1231.05,334.87,285.40,16.64,3,0.0164,1384.45
70,GSM8K,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,432.57,144.60,120.30,23.61,3,0.0142,1192.80
40,HumanEval,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,4193,0.4095,N/A,18.77,683.75,239.32,209.65,14.98,3,0.0234,2037.76
10,MTBench,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,967.43,348.74,297.20,21.17,3,0.0170,1454.59
25,GSM8K,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,636.98,223.63,195.00,16.08,3,0.0218,1906.69
85,HumanEval,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1857,0.1819,N/A,58.03,336.53,114.91,92.85,30.33,3,0.0113,921.41
55,MTBench,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1164.58,385.17,332.35,15.51,3,0.0213,1841.99
41,HumanEval,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0000,10240,4193,0.4095,N/A,18.77,708.39,264.17,209.65,14.46,3,0.0258,2037.76
26,GSM8K,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,660.53,247.60,195.00,15.50,3,0.0242,1906.69
11,MTBench,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,1007.14,389.58,297.20,20.33,3,0.0190,1454.59
56,MTBench,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1207.78,428.54,332.35,14.95,3,0.0237,1841.99
71,GSM8K,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,450.90,162.58,120.30,22.65,3,0.0159,1192.80
86,HumanEval,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0000,10208,1857,0.1819,N/A,58.03,353.33,131.50,92.85,28.89,3,0.0129,921.41
101,MTBench,5.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1269.55,373.73,285.40,16.13,3,0.0182,1384.45
116,GSM8K,5.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,489.44,146.84,106.25,20.92,3,0.0143,1050.62

## 方法: uncertainty_decoding

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
6,MTBench,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1715.28,573.40,572.80,11.97,3,0.0279,13.78
36,HumanEval,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.00,10271,6499,0.6328,N/A,55.20,983.81,325.39,324.95,10.44,3,0.0317,25.52
21,GSM8K,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.25,10276,6176,0.6010,N/A,58.24,934.29,309.18,308.80,11.00,3,0.0301,22.45
51,MTBench,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1374.55,503.32,499.30,13.16,3,0.0278,556.67
96,MTBench,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1515.53,460.34,451.80,13.55,3,0.0224,445.18
81,HumanEval,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.00,10225,3550,0.3472,N/A,37.91,509.20,179.32,177.50,20.08,3,0.0175,357.90
126,HumanEval,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.00,10263,4060,0.3956,N/A,35.31,689.78,206.33,203.00,14.88,3,0.0201,404.60
111,GSM8K,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.05,10258,3281,0.3198,N/A,27.54,576.75,167.93,164.05,17.79,3,0.0164,333.24
66,GSM8K,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.15,10236,4837,0.4725,N/A,53.79,675.41,243.90,241.85,15.16,3,0.0238,481.47
52,MTBench,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1388.03,517.12,499.30,13.03,3,0.0286,556.67
7,MTBench,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1715.69,575.03,572.80,11.97,3,0.0280,13.78
127,HumanEval,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.00,10263,4060,0.3956,N/A,35.31,696.40,212.69,203.00,14.74,3,0.0207,404.60
97,MTBench,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1529.91,473.22,451.80,13.42,3,0.0230,445.18
82,HumanEval,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.00,10225,3550,0.3472,N/A,37.91,515.17,185.58,177.50,19.85,3,0.0181,357.90
37,HumanEval,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.00,10271,6499,0.6328,N/A,55.20,986.64,326.95,324.95,10.41,3,0.0318,25.52
22,GSM8K,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.25,10276,6176,0.6010,N/A,58.24,935.42,310.54,308.80,10.99,3,0.0302,22.45
112,GSM8K,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.05,10258,3281,0.3198,N/A,27.54,586.29,173.90,164.05,17.50,3,0.0170,333.24
67,GSM8K,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.15,10236,4837,0.4725,N/A,53.79,682.22,250.99,241.85,15.00,3,0.0245,481.47
8,MTBench,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1718.27,577.11,572.80,11.95,3,0.0281,13.78
38,HumanEval,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.00,10271,6499,0.6328,N/A,55.20,987.89,328.95,324.95,10.40,3,0.0320,25.52
23,GSM8K,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.25,10276,6176,0.6010,N/A,58.24,937.48,312.28,308.80,10.96,3,0.0304,22.45
53,MTBench,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1404.78,532.93,499.30,12.87,3,0.0295,556.67
68,GSM8K,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.15,10236,4837,0.4725,N/A,53.79,690.81,259.19,241.85,14.82,3,0.0253,481.47
83,HumanEval,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.00,10225,3550,0.3472,N/A,37.91,521.65,192.59,177.50,19.60,3,0.0188,357.90
98,MTBench,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1544.43,487.84,451.80,13.30,3,0.0238,445.18
113,GSM8K,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.05,10258,3281,0.3198,N/A,27.54,591.24,180.58,164.05,17.35,3,0.0176,333.24
128,HumanEval,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.00,10263,4060,0.3956,N/A,35.31,703.64,219.86,203.00,14.59,3,0.0214,404.60

# 各数据集方法平均对比 (跨模型系列)

## 数据集: GSM8K (跨模型系列平均)

,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
方法,,,,,,,,,,,,,,
CEE-SD,20.3333,563.0,0.1583,10224.7778,2719.2222,0.2660,70.9400,493.9522,147.3756,135.9611,20.7122,5.0,0.0144,439.7967
tk_slt,20.3333,563.0,0.1583,10231.6667,2810.3333,0.2746,37.3633,514.2267,166.1067,140.5167,20.4667,3.0,0.0162,1383.3700
DSSD,20.3333,563.0,0.1542,10231.6667,2101.3333,0.2054,50.2167,736.0611,400.6800,105.0667,15.2556,3.0,0.0392,31232.1733
uncertainty_decoding,20.3333,563.0,0.1500,10256.6667,4764.6667,0.4644,46.5233,734.4344,245.3878,238.2333,14.5078,3.0,0.0239,279.0533
DSD,20.3333,563.0,0.1542,10231.4444,5188.6667,0.5071,69.6456,2154.9456,1629.2511,259.4333,6.1378,3.0,0.1593,188336.8367

## 数据集: HumanEval (跨模型系列平均)

,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
方法,,,,,,,,,,,,,,
CEE-SD,20.3333,563.0,0.0,10224.0000,1803.1667,0.1764,83.7900,332.0317,94.8283,90.1583,30.7983,5.0,0.0093,75.5150
tk_slt,24.0000,563.0,0.0,10226.2857,2938.0000,0.2872,38.9286,510.4129,170.1743,146.9000,22.3029,3.0,0.0167,1436.8829
DSSD,20.3333,563.0,0.0,10229.3333,1782.3333,0.1742,63.4233,623.1356,331.9800,89.1167,19.7889,3.0,0.0325,24793.7700
uncertainty_decoding,20.3333,563.0,0.0,10253.0000,4703.0000,0.4585,42.8067,732.6867,241.9622,235.1500,14.9989,3.0,0.0236,262.6733
DSD,20.3333,563.0,0.0,10229.3333,5218.8889,0.5101,69.7678,2132.9000,1604.1478,260.9444,6.1156,3.0,0.1568,184127.6378

## 数据集: MTBench (跨模型系列平均)

,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
方法,,,,,,,,,,,,,,
CEE-SD,20.3333,563.0,NaN,19567.0000,5649.6667,0.2915,63.2400,1020.7978,299.7644,282.4833,19.6033,5.0,0.0155,354.6644
tk_slt,20.3333,563.0,NaN,19672.3333,6099.6667,0.3123,29.2167,1121.1633,356.8456,304.9833,17.7856,3.0,0.0183,1560.3433
DSSD,20.3333,563.0,NaN,19670.6667,5213.3333,0.2700,41.4033,2007.5300,1195.8167,260.6667,13.3000,3.0,0.0628,56387.8733
uncertainty_decoding,20.3333,563.0,NaN,19720.3333,10159.3333,0.5166,50.9000,1545.1633,522.2567,507.9667,12.8022,3.0,0.0266,338.5433
DSD,20.3333,563.0,NaN,19660.3333,10313.5556,0.5257,64.1289,4553.0389,3517.2678,515.6778,5.9422,3.0,0.1819,222432.7144

# 实验结果对比表（按数据集分组）

## 数据集: GSM8K

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
27,GSM8K,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2922,0.2854,55.89,73.27,499.86,149.26,146.10,20.49,5,0.0146,314.37
72,GSM8K,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10197,2910,0.2854,76.79,67.21,474.62,150.65,145.50,21.48,5,0.0148,821.63
117,GSM8K,46.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,483.45,117.71,115.95,21.18,5,0.0115,130.05
28,GSM8K,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2923,0.2854,55.88,73.18,506.63,156.14,146.15,20.21,5,0.0152,320.51
73,GSM8K,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10193,2917,0.2862,76.91,67.25,488.75,164.56,145.85,20.86,5,0.0161,890.87
118,GSM8K,10.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,485.42,121.22,115.95,21.10,5,0.0118,130.05
29,GSM8K,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2375,10240,2924,0.2855,55.8,73.13,514.51,163.52,146.20,19.90,5,0.0160,321.54
74,GSM8K,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1875,10193,2920,0.2865,76.93,67.13,502.57,178.12,146.00,20.28,5,0.0175,899.10
119,GSM8K,5.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,2319,0.2265,74.69,72.43,489.76,125.20,115.95,20.91,5,0.0122,130.05
15,GSM8K,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,4566,0.4459,N/A,42.06,914.31,449.11,228.30,11.20,3,0.0439,105157.63
60,GSM8K,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,3511,0.3437,N/A,64.51,1143.02,806.70,175.55,8.94,3,0.0790,358582.20
105,GSM8K,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,3319,0.3241,N/A,70.54,1182.32,761.56,165.95,8.66,3,0.0744,330850.30
16,GSM8K,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,6335,0.6187,N/A,62.06,1408.46,775.30,316.75,7.27,3,0.0757,54278.14
61,GSM8K,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10214,5711,0.5591,N/A,79.41,2431.28,1940.00,285.55,4.20,3,0.1899,203526.82
106,GSM8K,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,5605,0.5474,N/A,83.38,2474.64,1844.62,280.25,4.14,3,0.1801,192415.74
17,GSM8K,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10240,6335,0.6187,N/A,62.06,1777.96,1144.41,316.75,5.76,3,0.1118,54278.14
62,GSM8K,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10214,5711,0.5591,N/A,79.41,4051.13,3558.90,285.55,2.52,3,0.3484,203526.82
107,GSM8K,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,5605,0.5474,N/A,83.38,4011.39,3382.66,280.25,2.55,3,0.3303,192415.74
18,GSM8K,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,468.38,143.87,106.70,21.86,3,0.0140,9293.82
63,GSM8K,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,558.37,236.39,112.10,18.29,3,0.0231,48449.04
108,GSM8K,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,553.36,193.14,96.40,18.50,3,0.0189,35953.66
19,GSM8K,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,542.04,217.23,106.70,18.89,3,0.0212,9293.82
64,GSM8K,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,862.40,539.85,112.10,11.84,3,0.0528,48449.04
109,GSM8K,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,782.96,423.88,96.40,13.08,3,0.0414,35953.66
20,GSM8K,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.2500,10240,2134,0.2084,N/A,48.94,622.55,298.42,106.70,16.45,3,0.0291,9293.82
65,GSM8K,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2242,0.2195,N/A,45.93,1190.86,868.79,112.10,8.58,3,0.0851,48449.04
110,GSM8K,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0500,10240,1928,0.1883,N/A,55.78,1043.63,684.55,96.40,9.81,3,0.0669,35953.66
24,GSM8K,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,614.78,201.37,195.00,16.66,3,0.0197,1906.69
69,GSM8K,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,414.04,126.45,120.30,24.67,3,0.0124,1192.80
114,GSM8K,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,456.51,112.22,106.25,22.43,3,0.0110,1050.62
25,GSM8K,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,636.98,223.63,195.00,16.08,3,0.0218,1906.69
70,GSM8K,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,432.57,144.60,120.30,23.61,3,0.0142,1192.80
115,GSM8K,10.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,472.29,129.67,106.25,21.68,3,0.0127,1050.62
26,GSM8K,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.2625,10240,3900,0.3809,N/A,21.01,660.53,247.60,195.00,15.50,3,0.0242,1906.69
71,GSM8K,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1625,10215,2406,0.2355,N/A,41.80,450.90,162.58,120.30,22.65,3,0.0159,1192.80
116,GSM8K,5.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10240,2125,0.2075,N/A,49.28,489.44,146.84,106.25,20.92,3,0.0143,1050.62
21,GSM8K,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10276,6176,0.6010,N/A,58.24,934.29,309.18,308.80,11.00,3,0.0301,22.45
66,GSM8K,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1500,10236,4837,0.4725,N/A,53.79,675.41,243.90,241.85,15.16,3,0.0238,481.47
111,GSM8K,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10258,3281,0.3198,N/A,27.54,576.75,167.93,164.05,17.79,3,0.0164,333.24
22,GSM8K,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10276,6176,0.6010,N/A,58.24,935.42,310.54,308.80,10.99,3,0.0302,22.45
67,GSM8K,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1500,10236,4837,0.4725,N/A,53.79,682.22,250.99,241.85,15.00,3,0.0245,481.47
112,GSM8K,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10258,3281,0.3198,N/A,27.54,586.29,173.90,164.05,17.50,3,0.0170,333.24
23,GSM8K,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.2500,10276,6176,0.6010,N/A,58.24,937.48,312.28,308.80,10.96,3,0.0304,22.45
68,GSM8K,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.1500,10236,4837,0.4725,N/A,53.79,690.81,259.19,241.85,14.82,3,0.0253,481.47
113,GSM8K,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0500,10258,3281,0.3198,N/A,27.54,591.24,180.58,164.05,17.35,3,0.0176,333.24

## 数据集: HumanEval

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
42,HumanEval,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1787,0.1745,44.57,90.35,332.56,91.08,89.35,30.79,5,0.0089,101.38
87,HumanEval,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1820,0.1783,77.9,77.27,326.20,92.22,91.00,31.29,5,0.0090,50.33
43,HumanEval,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1787,0.1745,44.57,90.35,336.65,94.91,89.35,30.42,5,0.0093,101.38
88,HumanEval,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1819,0.1782,77.9,77.21,326.61,94.35,90.95,31.25,5,0.0092,49.31
44,HumanEval,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1787,0.1745,44.57,90.35,341.23,99.38,89.35,30.01,5,0.0097,101.38
89,HumanEval,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1819,0.1782,77.9,77.21,328.94,97.03,90.95,31.03,5,0.0095,49.31
30,HumanEval,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,4912,0.4797,N/A,36.79,982.81,481.41,245.60,10.42,3,0.0470,113674.24
75,HumanEval,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,3114,0.3051,N/A,76.98,1008.16,710.82,155.70,10.13,3,0.0696,302622.24
120,HumanEval,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10240,3538,0.3455,N/A,64.18,1253.68,810.84,176.90,8.17,3,0.0792,360761.34
31,HumanEval,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,6546,0.6393,N/A,56.90,1464.94,809.06,327.30,6.99,3,0.0790,58100.74
76,HumanEval,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,5436,0.5325,N/A,88.45,2186.70,1720.65,271.80,4.67,3,0.1686,179203.98
121,HumanEval,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10240,5721,0.5587,N/A,79.63,2572.78,1936.10,286.05,3.98,3,0.1891,202740.74
32,HumanEval,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,6546,0.6393,N/A,56.90,1881.04,1225.37,327.30,5.44,3,0.1197,58100.74
77,HumanEval,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,5436,0.5325,N/A,88.45,3658.35,3192.38,271.80,2.79,3,0.3127,179203.98
122,HumanEval,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10240,5721,0.5587,N/A,79.63,4187.64,3550.70,286.05,2.45,3,0.3467,202740.74
33,HumanEval,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1471,0.1437,N/A,77.12,324.30,94.13,73.55,31.58,3,0.0092,2962.43
78,HumanEval,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1709,0.1674,N/A,64.89,408.95,164.94,85.45,24.96,3,0.0162,24246.27
123,HumanEval,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0,10240,2167,0.2116,N/A,48.26,626.39,227.27,108.35,16.35,3,0.0222,47172.61
34,HumanEval,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1471,0.1437,N/A,77.12,361.32,131.08,73.55,28.34,3,0.0128,2962.43
79,HumanEval,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1709,0.1674,N/A,64.89,569.46,325.54,85.45,17.93,3,0.0319,24246.27
124,HumanEval,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0,10240,2167,0.2116,N/A,48.26,923.71,524.41,108.35,11.09,3,0.0512,47172.61
35,HumanEval,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,0.0,10240,1471,0.1437,N/A,77.12,393.58,163.44,73.55,26.02,3,0.0160,2962.43
80,HumanEval,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,0.0,10208,1709,0.1674,N/A,64.89,747.20,503.26,85.45,13.66,3,0.0493,24246.27
125,HumanEval,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,0.0,10240,2167,0.2116,N/A,48.26,1253.31,853.75,108.35,8.17,3,0.0834,47172.61
39,HumanEval,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,4193,0.4095,N/A,18.77,660.96,216.08,209.65,15.49,3,0.0211,2037.76
84,HumanEval,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,1857,0.1819,N/A,58.03,320.18,98.54,92.85,31.88,3,0.0097,921.41
129,HumanEval,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10240,2416,0.2359,N/A,42.10,509.75,126.70,120.80,20.09,3,0.0124,1180.67
40,HumanEval,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,4193,0.4095,N/A,18.77,683.75,239.32,209.65,14.98,3,0.0234,2037.76
85,HumanEval,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,1857,0.1819,N/A,58.03,336.53,114.91,92.85,30.33,3,0.0113,921.41
41,HumanEval,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10240,4193,0.4095,N/A,18.77,708.39,264.17,209.65,14.46,3,0.0258,2037.76
86,HumanEval,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10208,1857,0.1819,N/A,58.03,353.33,131.50,92.85,28.89,3,0.0129,921.41
36,HumanEval,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10271,6499,0.6328,N/A,55.20,983.81,325.39,324.95,10.44,3,0.0317,25.52
81,HumanEval,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10225,3550,0.3472,N/A,37.91,509.20,179.32,177.50,20.08,3,0.0175,357.90
126,HumanEval,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10263,4060,0.3956,N/A,35.31,689.78,206.33,203.00,14.88,3,0.0201,404.60
37,HumanEval,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10271,6499,0.6328,N/A,55.20,986.64,326.95,324.95,10.41,3,0.0318,25.52
82,HumanEval,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10225,3550,0.3472,N/A,37.91,515.17,185.58,177.50,19.85,3,0.0181,357.90
127,HumanEval,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10263,4060,0.3956,N/A,35.31,696.40,212.69,203.00,14.74,3,0.0207,404.60
38,HumanEval,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,0.0,10271,6499,0.6328,N/A,55.20,987.89,328.95,324.95,10.40,3,0.0320,25.52
83,HumanEval,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,0.0,10225,3550,0.3472,N/A,37.91,521.65,192.59,177.50,19.60,3,0.0188,357.90
128,HumanEval,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,0.0,10263,4060,0.3956,N/A,35.31,703.64,219.86,203.00,14.59,3,0.0214,404.60

## 数据集: MTBench

,数据集,Edge-Cloud 带宽 (Mbps),Edge-End 带宽 (Mbps),方法,Little-Model,Draft-Model,Target-Model,准确率,生成 Token 数,目标模型 Forward 次数,目标模型 Forward/Token,Draft 接受率 (%),Target 接受率 (%),挂钟时间 (s),通信时间 (s),排队时间 (s),Token 输出速率 (tokens/s),Gamma1:,每Token 平均通信时间 (s),每token平均WAN通信数据量 (bytes)
12,MTBench,46.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.15,77.64,824.06,242.01,238.45,24.61,5,0.0119,158.71
57,MTBench,46.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6444,0.3592,58.02,49.13,1049.80,330.24,322.20,17.09,5,0.0184,634.83
102,MTBench,46.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1150.05,290.18,286.20,17.81,5,0.0142,173.57
13,MTBench,10.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.14,77.68,831.02,248.87,238.45,24.41,5,0.0123,158.19
58,MTBench,10.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6462,0.3602,57.89,48.85,1073.75,352.04,323.10,16.71,5,0.0196,774.54
103,MTBench,10.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1157.93,297.52,286.20,17.69,5,0.0145,173.57
14,MTBench,5.0,563,CEE-SD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20283,4769,0.2351,66.12,77.68,838.70,256.82,238.45,24.18,5,0.0127,158.19
59,MTBench,5.0,563,CEE-SD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,17938,6462,0.3602,57.89,48.85,1095.56,374.16,323.10,16.37,5,0.0209,786.81
104,MTBench,5.0,563,CEE-SD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,5724,0.2795,64.58,63.11,1166.31,306.04,286.20,17.56,5,0.0149,173.57
0,MTBench,46.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,7883,0.3849,N/A,54.02,1565.61,776.46,394.15,13.08,3,0.0379,87455.74
45,MTBench,46.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18003,7860,0.4366,N/A,43.89,2586.83,1843.51,393.00,6.96,3,0.1024,485829.15
90,MTBench,46.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,7643,0.3732,N/A,57.01,2693.97,1742.92,382.15,7.60,3,0.0851,398462.46
1,MTBench,10.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,11919,0.5820,N/A,72.40,2585.39,1413.07,595.95,7.92,3,0.0690,47171.58
46,MTBench,10.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18030,11003,0.6103,N/A,64.46,5139.06,4200.72,550.15,3.51,3,0.2330,249702.41
91,MTBench,10.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,11796,0.5760,N/A,74.26,5487.25,4180.76,589.80,3.73,3,0.2041,218199.55
2,MTBench,5.0,563,DSD,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,11919,0.5820,N/A,72.40,3234.91,2062.27,595.95,6.33,3,0.1007,47171.58
47,MTBench,5.0,563,DSD,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18030,11003,0.6103,N/A,64.46,8690.73,7752.23,550.15,2.07,3,0.4300,249702.41
92,MTBench,5.0,563,DSD,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,11796,0.5760,N/A,74.26,8993.60,7683.47,589.80,2.28,3,0.3752,218199.55
3,MTBench,46.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,808.92,247.44,188.25,25.32,3,0.0121,6735.36
48,MTBench,46.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,1750.88,758.75,352.85,10.31,3,0.0420,107093.35
93,MTBench,46.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,1385.47,504.45,240.90,14.78,3,0.0246,55334.91
4,MTBench,10.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,925.71,364.71,188.25,22.12,3,0.0178,6735.36
49,MTBench,10.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,2835.14,1842.03,352.85,6.37,3,0.1020,107093.35
94,MTBench,10.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,2065.31,1184.06,240.90,9.92,3,0.0578,55334.91
5,MTBench,5.0,563,DSSD,llama-68m,tiny-llama-1.1b,Llama-2-13b-hf,NaN,20480,3765,0.1838,N/A,57.24,1045.92,485.23,188.25,19.58,3,0.0237,6735.36
50,MTBench,5.0,563,DSSD,Qwen1.5-0.5B-Chat,Qwen1.5-1.8B-Chat,Qwen1.5-7B-Chat,NaN,18052,7057,0.3909,N/A,24.67,4409.62,3416.29,352.85,4.09,3,0.1892,107093.35
95,MTBench,5.0,563,DSSD,Qwen3-0.6B,Qwen3-1.7B,Qwen3-14B,NaN,20480,4818,0.2353,N/A,42.30,2840.80,1959.39,240.90,7.21,3,0.0957,55334.91
9,MTBench,46.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,927.08,309.65,297.20,22.09,3,0.0151,1454.59
54,MTBench,46.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1124.42,344.47,332.35,16.06,3,0.0191,1841.99
99,MTBench,46.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1191.44,296.86,285.40,17.19,3,0.0145,1384.45
10,MTBench,10.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,967.43,348.74,297.20,21.17,3,0.0170,1454.59
55,MTBench,10.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1164.58,385.17,332.35,15.51,3,0.0213,1841.99
100,MTBench,10.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1231.05,334.87,285.40,16.64,3,0.0164,1384.45
11,MTBench,5.0,563,tk_slt,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20480,5944,0.2902,N/A,31.50,1007.14,389.58,297.20,20.33,3,0.0190,1454.59
56,MTBench,5.0,563,tk_slt,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18057,6647,0.3681,N/A,22.41,1207.78,428.54,332.35,14.95,3,0.0237,1841.99
101,MTBench,5.0,563,tk_slt,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20480,5708,0.2787,N/A,33.74,1269.55,373.73,285.40,16.13,3,0.0182,1384.45
6,MTBench,46.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1715.28,573.40,572.80,11.97,3,0.0279,13.78
51,MTBench,46.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1374.55,503.32,499.30,13.16,3,0.0278,556.67
96,MTBench,46.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1515.53,460.34,451.80,13.55,3,0.0224,445.18
7,MTBench,10.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1715.69,575.03,572.80,11.97,3,0.0280,13.78
52,MTBench,10.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1388.03,517.12,499.30,13.03,3,0.0286,556.67
97,MTBench,10.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1529.91,473.22,451.80,13.42,3,0.0230,445.18
8,MTBench,5.0,563,uncertainty_decoding,llama-68m,llama-68m,Llama-2-13b-hf,NaN,20539,11456,0.5578,N/A,65.72,1718.27,577.11,572.80,11.95,3,0.0281,13.78
53,MTBench,5.0,563,uncertainty_decoding,Qwen1.5-0.5B-Chat,Qwen1.5-0.5B-Chat,Qwen1.5-7B-Chat,NaN,18083,9986,0.5522,N/A,49.15,1404.78,532.93,499.30,12.87,3,0.0295,556.67
98,MTBench,5.0,563,uncertainty_decoding,Qwen3-0.6B,Qwen3-0.6B,Qwen3-14B,NaN,20539,9036,0.4399,N/A,37.83,1544.43,487.84,451.80,13.30,3,0.0238,445.18

表格已保存到 experiment_results_table.md 文件中